version: '3.9'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    restart: always
    ports:
      - '5000:5000'
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - server

volumes:
  mongo-data:
